window.termDefs = {
  example: { title: 'Hover Demo', body: '對,就是這樣!像這樣有紅色波浪底線的字,把滑鼠移過去就會跳出說明。' },
  kernel: { title: 'Kernel / Filter', body: 'CNN 裡的小窗戶,通常 3×3 或 5×5。滑過整張圖做點積運算,輸出 feature map。每個 kernel 偵測一種特徵(邊、紋理、色塊等)。', link: { text: 'PyTorch Conv2d 文件', url: 'https://docs.pytorch.org/docs/stable/generated/torch.nn.Conv2d.html' } },
  cnn: { title: 'CNN — Convolutional Neural Network', body: '使用卷積層當主要組件的神經網路。三大特性:Local Connectivity、Weight Sharing、Hierarchical Features。', link: { text: 'CS231n 教材', url: 'https://cs231n.github.io/convolutional-networks/' } },
  learn: { title: 'Learning by Backpropagation', body: 'kernel 的數值不是預先設定,而是訓練時透過反向傳播計算梯度,慢慢調整出來的。訓練完的第一層 kernel 通常會自己長成像 Sobel 那樣的邊緣偵測器。' },
  receptive: { title: 'Receptive Field 感受野', body: '輸出某個位置「看得到」原圖多大範圍。一層 3×3 感受野 = 3×3,兩層疊起來 = 5×5。深層 neuron 的感受野會涵蓋整張圖,所以才能識別「物件」這種大範圍的東西。' },
  dotproduct: { title: '點積 (Dot Product)', body: '對應位置相乘再全部加起來。例如 [1,2,3] · [4,5,6] = 1×4 + 2×5 + 3×6 = 32。卷積就是讓 kernel 跟圖片的每個 3×3 區塊都做一次點積。' },
  vgg: { title: 'VGG (2014)', body: '牛津大學提出的 CNN,證明「很多個 3×3 conv 疊起來」效果比少數幾個大 kernel 好。從此 3×3 成為共識。', link: { text: 'VGG 論文', url: 'https://arxiv.org/abs/1409.1556' } },
  featuremap: { title: 'Feature Map', body: '一個 kernel 滑過整張圖後輸出的 2D 矩陣。如果該 kernel 是「橫線偵測器」,那 feature map 上亮的地方就代表「這裡有橫線」。' },
  padding: { title: 'Padding', body: '在輸入圖周圍補一圈(或多圈)0。這樣卷積後尺寸不會變小。padding=1 + kernel=3 + stride=1 → "same" padding。' },
  stride: { title: 'Stride', body: 'kernel 一次滑幾格。stride=1 是逐格滑,stride=2 等於每兩格取一個 → 輸出尺寸減半。' },
  pooling: { title: 'Pooling 池化', body: 'CNN 中的下採樣操作。在固定窗戶內取代表值(最大、平均),減少 H/W 尺寸。沒有可學參數,純粹是固定的運算。' },
  maxpool: { title: 'Max Pooling', body: '取窗戶內最大值。最常用,因為保留最強特徵 — 「有偵測到 = 數值大 = 留下」。', link: { text: 'PyTorch MaxPool2d', url: 'https://docs.pytorch.org/docs/stable/generated/torch.nn.MaxPool2d.html' } },
  avgpool: { title: 'Average Pooling', body: '取窗戶內平均值。比較少用於分類,但 GAP 用平均做最後壓縮。' },
  gap: { title: 'Global Average Pooling', body: '把整張 feature map 取平均,輸出一個值。用來取代 FC 層,省非常多參數。ResNet 之後標配。' },
  strideconv: { title: 'Stride Conv 取代 Pool', body: '用 stride=2 的 conv 同樣可以下採樣,而且有可學參數,讓模型自己決定怎麼壓縮。Darknet-53、現代架構多用這個。' },
  activation: { title: '激活函數', body: '在每層 conv/linear 之後加的非線性函數。沒有它,N 層神經網路化簡後等於 1 層 — 完全無用。' },
  saturate: { title: '飽和 (Saturation)', body: '某些函數(如 sigmoid)在輸入很大或很小時,輸出會「卡住」在 0 或 1 附近,梯度變成接近 0 → 訓練不動。ReLU 解決了這個問題。' },
  leaky: { title: 'Leaky ReLU', body: 'ReLU 的負半邊改成 0.01×x 而不是 0,這樣負值也有梯度,不會 dying。' },
  mish: { title: 'Mish', body: 'f(x) = x × tanh(softplus(x))。平滑、非單調的 activation,YOLOv4 用這個。', link: { text: 'Mish 論文', url: 'https://arxiv.org/abs/1908.08681' } },
  silu: { title: 'SiLU / Swish', body: 'f(x) = x × sigmoid(x)。平滑版本的 ReLU,YOLOv5+、Transformer 都用。也叫 Swish。', link: { text: 'Swish 論文', url: 'https://arxiv.org/abs/1710.05941' } },
  bn: { title: 'Batch Normalization', body: '把每個 batch 的 activation 標準化:y = γ×(x−μ)/σ + β。加速收斂、穩定訓練、可用更大 LR。', link: { text: 'BN 論文', url: 'https://arxiv.org/abs/1502.03167' } },
  lr: { title: 'Learning Rate', body: '梯度下降的步伐大小。太大會震盪,太小訓練很慢。BN 讓你可以用更大的 LR。' },
  runningstats: { title: 'Running Statistics', body: 'BN 在訓練時用當前 batch 的 mean/std,但會同時記錄 momentum 移動平均。eval 時用這個 running stats,因為單筆推論沒有 batch 可以算。' },
  fc: { title: 'Fully Connected Layer', body: '每個輸入連接到每個輸出。最簡單但參數最多的層。現代 CNN 多半只在最後一層當分類器。', link: { text: 'PyTorch nn.Linear', url: 'https://docs.pytorch.org/docs/stable/generated/torch.nn.Linear.html' } },
  weightshare: { title: '權重共享 (Weight Sharing)', body: '同一個 kernel 的參數被應用到圖片的每個位置。一個 3×3 kernel 永遠只有 9 個參數,不管圖多大。' },
  gradient: { title: '梯度 (Gradient)', body: 'loss 對某個參數的偏導數,告訴模型「往哪個方向、多大幅度調這個參數會讓 loss 變小」。梯度為 0 = 完全卡住。' },
  chainrule: { title: '連鎖律 (Chain Rule)', body: '微積分基本工具。如果 y = f(g(x)),那 dy/dx = f\'(g(x)) × g\'(x)。深度學習的反向傳播就是不斷用這個規則把梯度傳回去。' },
  skip: { title: 'Skip Connection', body: '把 input 直接加到 output 的捷徑路徑:y = F(x) + x。讓梯度可以「不經過中間運算」就傳回前面層,解決梯度消失。', link: { text: 'ResNet 論文', url: 'https://arxiv.org/abs/1512.03385' } },
  resnet1k: { title: 'ResNet 1000+ 層', body: 'Pre-activation ResNet (v2) 改良後可以訓練到 1000+ 層還不會劣化。', link: { text: 'ResNet v2', url: 'https://arxiv.org/abs/1603.05027' } },
  backprop: { title: '反向傳播 (Backpropagation)', body: '從 loss 開始,用連鎖律一路把梯度算回每個參數。PyTorch 的 .backward() 自動幫你做。' },
  residual: { title: '殘差學習', body: '不直接學 H(x),而是學 F(x) = H(x) − x。再用 y = F(x) + x 還原。這樣模型只要學「該加什麼」,簡單很多。' },
  yolo: { title: 'YOLO — You Only Look Once', body: '即時物件偵測模型的開山之作 (2016)。把整張圖切成 grid,一次預測所有物件。', link: { text: 'YOLOv1 論文', url: 'https://arxiv.org/abs/1506.02640' } },
  grid: { title: 'Grid Cell', body: 'YOLO 把輸入圖切成 SxS 格子。每個格子負責預測中心落在它裡面的物件。' },
  anchorbased: { title: 'Anchor-based', body: '預先定義幾個常見的 box 形狀,模型只要預測「相對 anchor 的調整量」。比直接預測絕對座標好學。' },
  anchorfree: { title: 'Anchor-free', body: '不用預設 anchor,直接預測物件中心 + 寬高。簡化 pipeline,YOLOv8 改回這個方式。' },
  responsible: { title: '"負責" 的格子', body: '物件中心落在哪個 grid cell,該 cell 就「負責」預測這個物件。其他 cell 預測背景。' },
  kmeans: { title: 'K-means Clustering', body: '非監督分群演算法。YOLOv2+ 訓練前會跑 k-means 在 GT box 上,找出 K 個最有代表性的 box 形狀當 anchor。' },
  v8anchor: { title: 'YOLOv8 Anchor-free', body: '2023 Ultralytics 發布的 YOLOv8 拋棄 anchor,改用 anchor-free + decoupled head。', link: { text: 'Ultralytics Docs', url: 'https://docs.ultralytics.com' } },
  iou: { title: 'IoU — Intersection over Union', body: '兩個 box 的「交集面積 / 聯集面積」。是衡量兩個 box 重疊程度的標準指標,範圍 0~1。IoU > 0.5 通常算 match。' },
  nms: { title: 'NMS — Non-Maximum Suppression', body: '後處理步驟。模型常會對同一物件預測多個 box,NMS 取 confidence 最高的,把跟它 IoU 太高的其他 box 丟掉。' },
  pytorch: { title: 'PyTorch', body: 'Meta 開發的深度學習框架。動態圖、Pythonic、debug 友善,目前主流。', link: { text: 'pytorch.org', url: 'https://pytorch.org' } },
  nnmodule: { title: 'nn.Module', body: 'PyTorch 所有模型的基底類別。繼承它就能自動管理 parameters、用 .cuda() 搬 GPU、用 .train()/.eval() 切換模式。', link: { text: 'nn.Module 文件', url: 'https://docs.pytorch.org/docs/stable/generated/torch.nn.Module.html' } },
  forward: { title: 'forward()', body: '定義模型怎麼處理輸入。寫好 forward,backward 就完全自動 — PyTorch 用 autograd 自動建 graph。' },
  shape: { title: 'Tensor Shape', body: 'PyTorch 圖像 tensor 的 shape 是 (Batch, Channel, Height, Width)。Debug 時印 shape 是最常用的招。' },
  'kernel-identity': { title: 'Identity Kernel', body: '中心 = 1,其他 = 0。輸出等於輸入,什麼都不改。是 baseline 對照組。' },
  'kernel-edge': { title: 'Edge Detection', body: '中心 8,周圍 -1。任何方向的邊緣都會被增強。' },
  'kernel-sobel-x': { title: 'Sobel X', body: '左 -1, 中 0, 右 +1。偵測「水平方向上的亮度變化」=「垂直邊緣」。' },
  'kernel-sobel-y': { title: 'Sobel Y', body: '上 -1, 中 0, 下 +1。偵測「垂直方向上的亮度變化」=「水平邊緣」。' },
  'kernel-blur': { title: 'Box Blur', body: '所有位置都是 1/9。等於取 3×3 區域的平均,讓圖變模糊。' },
  'kernel-sharpen': { title: 'Sharpen', body: '中心 5,十字 -1。把每個像素跟周圍的差異「放大」,讓邊緣看起來更清楚。' },
  'kernel-emboss': { title: 'Emboss', body: '不對稱 kernel(左上負,右下正)。產生「光從左上照」的浮雕效果。' },
  'layer-conv': { title: 'Conv2d 3×3', body: '最常用的卷積層,kernel 3×3, padding=1, stride=1,輸出 H/W 跟輸入一樣。', link: { text: 'PyTorch 文件', url: 'https://docs.pytorch.org/docs/stable/generated/torch.nn.Conv2d.html' } },
  'layer-convdown': { title: 'Conv2d 3×3 with stride=2', body: '用 stride=2 做下採樣的卷積。輸出 H/W 減半。現代架構用這個取代 MaxPool。' },
  'layer-bn': { title: 'Batch Normalization', body: '對每個 batch 做標準化:y = γ × (x - μ) / σ + β。', link: { text: 'BN 論文', url: 'https://arxiv.org/abs/1502.03167' } },
  'layer-relu': { title: 'ReLU', body: 'f(x) = max(0, x)。最常用的激活函數,計算超快。' },
  'layer-maxpool': { title: 'MaxPool 2×2', body: '取 2×2 區域內最大值,H/W 減半。' },
  'layer-gap': { title: 'Global Average Pooling', body: '把每個 channel 整張 feature map 取平均,輸出 (B, C, 1, 1)。取代 FC 層用。' },
  'layer-flatten': { title: 'Flatten', body: '把 (B, C, H, W) 攤平成 (B, C×H×W)。' },
  'layer-fc': { title: 'Fully Connected (Linear)', body: '每個輸入連接到每個輸出。預設輸出 1000(模擬 ImageNet)。', link: { text: 'nn.Linear', url: 'https://docs.pytorch.org/docs/stable/generated/torch.nn.Linear.html' } },
  'layer-residual': { title: 'Residual Block', body: 'ResNet 核心:Conv → BN → ReLU → Conv → BN → 加上 input → ReLU。' }
};
